/*
 * This source file was generated by the Gradle 'init' task
 */
package finsim

import spock.lang.Specification

class AppTest extends Specification {
    def "one is one"() {
        expect:
        1 == 1
    }
}
